### ISSUE TITLE
Path must be a string error

### ISSUE THREAD

**Issue by mzakrzewski** [komushi/cf-redis-commander#2]
Trying to use this but it's failing to start with the following error:

path.js:7
  throw new TypeError('Path must be a string. Received ' + inspect(path));
TypeError: Path must be a string. Received undefined
  at asertPath (path.js:7:11)
  at Object.dirname (path.js:1330:5)
  at Deps.lookupPackage (/home/vcap/deps/0/node_modules/module-deps/index.js:452:29)
  at Deps._transform (/home/vcap/deps/0/node_modules/module-deps/index.js:93:10)
  at Deps.Transform._read (/home/vcap/deps/0/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at Deps.Transform._write (/home/vcap/deps/0/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at Labeled.Pipeline._write (/home/vcap/deps/0/node_modules/stream-splicer/index.js:73:22)
  at doWrite (/home/vcap/deps/0/node_modules/readable-stream/lib/_stream_writable.js:279:12)
  at writeOrBuffer (/home/vcap/deps/0/node_modules/readable-stream/lib/_stream_writable.js:266:5)
  at Labeled.Writable.write (/home/vcap/deps/0/node_modules/readable-stream/lib/_stream_writable.js:211:11)
  exec error: Error: Command failed: ./node_modules/.bin/redis-commander --redis-port [port intentionally excluded] --redis-host [ip intentionally excluded] --redis-password [password intentionally excluded] --http-auth-username admin --http-auth-password pass --port 8080

Any thoughts?

**Comment by mzakrzewski** [comment]
This was resolved by upgrading the version of redis-commander within the package.json file to ^0.4.5.
